### ISSUE TITLE
Option to not show contribution numbers

### ISSUE THREAD

**Issue by gleich** [cjdenio/contributor_list#5]
I would love to use this on more of my projects but I don't like that it commits every time and then I have to pull the changes. It would be great if I could turn off the contribution numbers so it only updates when as new contributor gets added.

**Comment by cjdenio** [comment]
That's definitely the next thing on my to-do list! I hate it too :grimacing: 
https://github.com/cjdenio/contributor_list/issues/3

**Comment by gleich** [comment]
Once this feature gets added I will add this to all of my projects!

**Comment by cjdenio** [comment]
@Matt-Gleich Should be fixed now, just awaiting confirmation from the GH logs :smile:

**Comment by gleich** [comment]
Awesome @cjdenio thank you for this!

**Comment by cjdenio** [comment]
Yep, all fixed! :tada: 
You'll probably need to manually remove the `(x contributors)` on any projects that already use this.
